spring:
  profiles:
    active: test
    
ordernotiry: false
loginpass: '{cipher}941c15446567e8211931cf0d25f81696871f5a5ea74fac46638eed71db24e76b'
---

spring:
  profiles: test
  application:
    name: config-test

server:
  port:8006
---
spring:
  profiles: prod
  application:
    name: config-prod

server:
  port:8007
